#!/usr/bin/env bash

# if rofi >= 1.5.2 "Lock \x00icon\x1ffile-browser," works

entries=" Lock, Logout, Suspend, Reboot, Shutdown"

selected=$(echo $entries | rofi -m 0 -dmenu -sep ',' -p "" -theme ~/.config/rofi/power.rasi -i | sed 's/[^a-zA-Z0-9]//g' | awk '{print tolower($1)}')

lock() {
    ~/.local/bin/scripts/i3lock.sh
}

case $selected in
  lock) 
    lock;;
  logout)
    i3-msg exit;;
  suspend)
    lock && systemctl suspend;;
  reboot)
    systemctl reboot;;
  shutdown)
    systemctl poweroff -i;;
esac
